title: Jérémy BERNIER
email: jeremy.bernier@hotmail.fr
description: Jérémy BERNIER port-folio
baseurl: ""
url: "https://j-bernier.github.io"
urldev: "http://localhost:4000"
twitter_username: TheMJ_1
facebook_username: Mjerem
github_username: j-bernier
instagram_username: Mjeremn1