title: Jérémy BERNIER
email: jeremy.bernier@hotmail.fr
description: Jérémy BERNIER port-folio
twitter_username: TheMJ_1
facebook_username: Mjerem
github_username: j-bernier
instagram_username: Mjeremn1

collections:
  jobs:
    output: true