#docker_compose.yml

jekyll:
    image: jekyll/jekyll:pages
    command: jekyll serve --incremental --force_polling
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll
    environment:
      JEKYLL_UID: 1001
      JEKYLL_GID: 1001